version: '3.3'

services:
  go-bank-transfer:
    container_name: 'go-bank-transfer'
    image: go-bank-transfer:dev
    ports:
      - '3001:3001'
    volumes:
      - ./:/go-bank-transfer
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongodb:/docker-entrypoint-initdb.d