version: "3.3"

services:
  go-bank-transfer:
    container_name: "go-bank-transfer"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./:/go-bank-transfer
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    depends_on:
      - mongodb
      - postgres

  mongodb:
    container_name: "mongodb"
    image: "mongo:3.6.2"
    ports:
      - 27017:27017
    volumes:
      - ./script/mongodb:/docker-entrypoint-initdb.d

  postgres:
    container_name: "postgres"
    image: "postgres:12.2-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bank
    volumes:
      - ./script/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

#  go-bank-transfer-debug:
#    container_name: "go-bank-transfer-debug"
#    build:
#      context: .
#      dockerfile: Dockerfile.debug
#    ports:
#      - 3001:3001
#      - 40000:40000
#    volumes:
#      - ./:/go-bank-transfer
#      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
#    security_opt:
#      - "seccomp:unconfined"
#    cap_add:
#      - SYS_PTRACE
#    env_file:
#      - .env
#    depends_on:
#      - mongodb
#      - postgres