version: '3.3'

services:
  go-stone:
    container_name: 'go-stone'
    build: .
    ports:
      - '3001:3001'
    volumes:
      - ./:/go-stone
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongodb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev